# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[main]]
identifier = "stepik"
name = "Stepik"
url = "https://stepik.org/course/269329"

[main.params]
icon = "link"
newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/FedoseevSM"

[social.params]
icon = "brand-github"

[[social]]
identifier = "tenchat"
name = "TenChat"
url = "https://m.tenchat.ru/u/AkcKhjVM"

[[social]]
identifier = "links"
name = "Подробнее"
url = "https://fedoseevsm.github.io/p/semion-freelance-7-stran-uspeha/"

[[social]]
identifier = "telegram"
name = "Telegram"
url = "https://tglink.ru/semyonfedoseev"

[[social]]
identifier = "setka"
name = "Setka"
url = "https://setka.ru/accounts/34fa8040-47fb-4474-a94a-67d461712261"

# [social.params]
# icon = "instagram"
